CREATE DATABASE python_dados;
use python_dados;
	CREATE TABLE CPUS(
	idCpu INT PRIMARY KEY AUTO_INCREMENT,
	CPU1 VARCHAR(45),
	CPU2 FLOAT,
	CPU3 float
	);
    
    CREATE TABLE MEMO(
	idCpu INT PRIMARY KEY AUTO_INCREMENT,
	MEMO1 FLOAT,
	MEMO2 FLOAT,
	MEMO3 float
	);
    
    CREATE TABLE DISCO(
    idDisco INT PRIMARY KEY AUTO_INCREMENT,
    DISCO1 FLOAT,
    DISCO2 FLOAT,
    DISCO3 float
    );
    
SELECT * FROM CPUS;
SELECT * FROM MEMO;
SELECT * FROM DISCO;